
# ===============================
# | Service Info                |
# ===============================
api-version: /api/v1.0
service.name: template
port: 8081
# ===========================================================================================
# | MySQL                                                                                   |
# ===========================================================================================
db.user: root
db.host: 127.0.0.1
db.port: 3306
db.password: 123456
db.dbname: test
db.timeouts: 10s
db.maxconnections: 200
db.maxidleconns: 30
# ===============================
# | Redis                       |
# ===============================
redis.host: 127.0.0.1
redis.port: 6379
redis.password: 
redis.database: 1
redis.timeout: 0
# ===============================
# | ELK                         |
# ===============================
logstash.host: 127.0.0.1
logstash.port: 5000